# Generated by Django 4.1.7 on 2023-04-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='userId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='teachercourse',
            old_name='userId',
            new_name='userName',
        ),
    ]
