# Generated by Django 4.1.7 on 2023-03-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_userid_accountdetail_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='userName',
            new_name='Id',
        ),
    ]
