# Generated by Django 4.1.7 on 2023-03-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_rename_username_accountdetail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachercourse',
            old_name='userName',
            new_name='Id',
        ),
    ]
