# Generated by Django 4.1.7 on 2023-03-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_chapter_materials_alter_chapter_tests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='materials',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='tests',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='video',
            field=models.CharField(max_length=5000),
        ),
    ]
